name: HTML5 Validator
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.6.1
      with:
        # Path of the files to test
        root: public
        # Path of config file
        config: # optional
        # Extra arguments to test with
        extra: # optional
        # Format for logging output. Valid values: gnu,xml,json,text
        format: # optional
        # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
        log_level: # optional, default is WARNING
        # Checks css as well
        css: # optional
        # Files or directories to ignore in checking
        blacklist: # optional
        # Flag that increase verbose output only used for troubleshooting the action.
        action_debug: # optional
