name: HTML5 Validator
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.6.1
      with:
        # Path of the files to test
        root: public
